In [2]:
import pandas as pd
df = pd.read_csv(r"D:\python\popular_anime.csv")
df.head()

,id,name,genres,type,episodes,status,aired_from,aired_to,duration_per_ep,score,scored_by,rank,rating,studios,producers,image,trailer,synopsis
0,52991,Frieren: Beyond Journey's End,"Adventure, Drama, Fantasy",TV,28.0,Finished Airing,2023-09-29T00:00:00+00:00,2024-03-22T00:00:00+00:00,24 min per ep,9.30,676737.0,1.0,PG-13 - Teens 13 or older,Madhouse,"Aniplex, Dentsu, Shogakukan-Shueisha Productio...",https://cdn.myanimelist.net/images/anime/1015/...,https://www.youtube.com/watch?v=ZEkwCGJ3o7M,During their decade-long quest to defeat the D...
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy",TV,64.0,Finished Airing,2009-04-05T00:00:00+00:00,2010-07-04T00:00:00+00:00,24 min per ep,9.10,2223666.0,2.0,R - 17+ (violence & profanity),Bones,"Aniplex, Square Enix, Mainichi Broadcasting Sy...",https://cdn.myanimelist.net/images/anime/1208/...,https://www.youtube.com/watch?v=1ac3_YdSSy0,After a horrific alchemy experiment goes wrong...
2,9253,Steins;Gate,"Drama, Sci-Fi, Suspense",TV,24.0,Finished Airing,2011-04-06T00:00:00+00:00,2011-09-14T00:00:00+00:00,24 min per ep,9.07,1467570.0,3.0,PG-13 - Teens 13 or older,White Fox,"Frontier Works, Media Factory, Kadokawa Shoten...",https://cdn.myanimelist.net/images/anime/1935/...,https://www.youtube.com/watch?v=27OZc-ku6is,Eccentric scientist Rintarou Okabe has a never...
3,38524,Attack on Titan Season 3 Part 2,"Action, Drama, Suspense",TV,10.0,Finished Airing,2019-04-29T00:00:00+00:00,2019-07-01T00:00:00+00:00,23 min per ep,9.05,1700946.0,4.0,R - 17+ (violence & profanity),Wit Studio,"Production I.G, Dentsu, Mainichi Broadcasting ...",https://cdn.myanimelist.net/images/anime/1517/...,https://www.youtube.com/watch?v=hKHepjfj5Tw,Seeking to restore humanity's diminishing hope...
4,28977,Gintama Season 4,"Action, Comedy, Sci-Fi",TV,51.0,Finished Airing,2015-04-08T00:00:00+00:00,2016-03-30T00:00:00+00:00,24 min per ep,9.05,264260.0,5.0,PG-13 - Teens 13 or older,Bandai Namco Pictures,"TV Tokyo, Aniplex, Dentsu",https://cdn.myanimelist.net/images/anime/3/720...,NaN,"Gintoki, Shinpachi, and Kagura return as the f..."

In [3]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
28820    False
28821    False
28822    False
28823    False
28824    False
Length: 28825, dtype: bool

In [6]:
df[df["episodes"]<20]

,id,name,genres,type,episodes,status,aired_from,aired_to,duration_per_ep,score,scored_by,rank,rating,studios,producers,image,trailer,synopsis
3,38524,Attack on Titan Season 3 Part 2,"Action, Drama, Suspense",TV,10.0,Finished Airing,2019-04-29T00:00:00+00:00,2019-07-01T00:00:00+00:00,23 min per ep,9.05,1700946.0,4.0,R - 17+ (violence & profanity),Wit Studio,"Production I.G, Dentsu, Mainichi Broadcasting ...",https://cdn.myanimelist.net/images/anime/1517/...,https://www.youtube.com/watch?v=hKHepjfj5Tw,Seeking to restore humanity's diminishing hope...
5,60022,One Piece Fan Letter,"Action, Adventure, Fantasy",TV Special,1.0,Finished Airing,2024-10-20T00:00:00+00:00,NaN,24 min,9.04,83738.0,7.0,PG-13 - Teens 13 or older,Toei Animation,NaN,https://cdn.myanimelist.net/images/anime/1455/...,https://www.youtube.com/watch?v=MewJ5bEM-5U,Although the golden age of piracy is about to ...
6,39486,Gintama: The Very Final,"Action, Comedy, Drama, Sci-Fi",Movie,1.0,Finished Airing,2021-01-08T00:00:00+00:00,NaN,1 hr 44 min,9.04,80788.0,6.0,PG-13 - Teens 13 or older,Bandai Namco Pictures,"TV Tokyo, Aniplex, Dentsu, Bandai, Warner Bros...",https://cdn.myanimelist.net/images/anime/1245/...,https://www.youtube.com/watch?v=Zn1filVUyf8,Two years have passed following the Tendoshuu'...
9,15417,Gintama: Enchousen,"Action, Comedy, Sci-Fi",TV,13.0,Finished Airing,2012-10-04T00:00:00+00:00,2013-03-28T00:00:00+00:00,24 min per ep,9.02,173888.0,10.0,PG-13 - Teens 13 or older,Sunrise,"TV Tokyo, Aniplex, Dentsu, Shueisha, Miracle Bus",https://cdn.myanimelist.net/images/anime/1452/...,NaN,"While Gintoki Sakata was away, the Yorozuya fo..."
11,41467,Bleach: Thousand-Year Blood War,"Action, Adventure, Supernatural",TV,13.0,Finished Airing,2022-10-11T00:00:00+00:00,2022-12-27T00:00:00+00:00,24 min per ep,8.99,341015.0,12.0,R - 17+ (violence & profanity),Pierrot,"TV Tokyo, Aniplex, Dentsu, Shueisha",https://cdn.myanimelist.net/images/anime/1908/...,https://www.youtube.com/watch?v=e8YBesRKq_U,Substitute Soul Reaper Ichigo Kurosaki spends ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28820,16796,Mujeokcheorin Rambot,"Action, Sci-Fi",Movie,1.0,Finished Airing,1985-01-01T00:00:00+00:00,NaN,1 hr 10 min,NaN,NaN,18282.0,NaN,NaN,NaN,https://cdn.myanimelist.net/images/anime/5/451...,NaN,NaN
28821,48866,Hua Jianghu: Huan Shi Men Sheng 2nd Season,"Drama, Fantasy, Mystery, Romance",ONA,19.0,Finished Airing,2021-05-12T00:00:00+00:00,2021-08-25T00:00:00+00:00,20 min per ep,NaN,NaN,21550.0,PG-13 - Teens 13 or older,Rocen,NaN,https://cdn.myanimelist.net/images/anime/1037/...,NaN,Second season of Hua Ji
28822,16790,Super Samchongsa,"Action, Sci-Fi",Movie,1.0,Finished Airing,1982-01-01T00:00:00+00:00,NaN,1 hr 16 min,NaN,NaN,14907.0,NaN,NaN,NaN,https://cdn.myanimelist.net/images/anime/13/45...,NaN,A Korean animated movie about three kids prote...
28823,16788,Sengoku Bushou Retsuden Bakufuu Douji Hissatsuman,"Action, Adventure",OVA,3.0,Finished Airing,1990-06-22T00:00:00+00:00,1990-10-25T00:00:00+00:00,35 min per ep,NaN,NaN,14261.0,R+ - Mild Nudity,NaN,"Bandai Visual, Artmic",https://cdn.myanimelist.net/images/anime/11/45...,NaN,NaN
28824,16784,Marin X,"Action, Adventure, Sci-Fi",Movie,1.0,Finished Airing,1982-01-01T00:00:00+00:00,NaN,1 hr 20 min,NaN,NaN,17871.0,NaN,NaN,NaN,https://cdn.myanimelist.net/images/anime/13/45...,NaN,A Korean animated movie mixing Mecha w

In [8]:
d = df.groupby("type")
for i,v in d:
    print(i)
    print(v)

CM
          id                                               name  \
735    42166                              Violet Evergarden CMs
1584   36064                                   Fate/Grand Order
1998   48953  Natsume's Book of Friends: A Day Out in Hitoyo...
2131   53933                                       Proof of Two
2973   22839                                         Cross Road
...      ...                                                ...
27286  29749                  Convenience Store Senki Purin-tai
27328  42542                        Pittarazu Gekijou Manner CM
27371  29359                                   Bazar dé Gozarre
27381  42698             Nissan Note x The World of Golden Eggs
27613  43321                          Cancerfund x Din Dong CMs

                genres type  episodes            status  \
735              Drama   CM       2.0   Finished Airing
1584   Action, Fantasy   CM       NaN  Currently Airing
1998     Slice of Life   CM       1.0   Finished Airing
2131             Drama   CM       1.0   Finished Airing
2973     Slice of Life   CM       1.0   Finished Airing
...                ...  ...       ...               ...
27286           Comedy   CM       8.0   Finished Airing
27328           Comedy   CM       9.0   Finished Airing
27371           Comedy   CM      33.0   Finished Airing
27381           Comedy   CM       5.0   Finished Airing
27613           Comedy   CM       5.0   Finished Airing

                      aired_from                   aired_to duration_per_ep  \
735    2016-05-27T00:00:00+00:00  2017-03-16T00:00:00+00:00   38 sec per ep
1584   2014-12-27T00:00:00+00:00                        NaN          15 sec
1998   2021-04-21T00:00:00+00:00                        NaN           2 min
2131   2022-12-23T00:00:00+00:00                        NaN           4 min
2973   2014-02-25T00:00:00+00:00                        NaN           2 min
...                          ...                        ...             ...
27286  2008-01-01T00:00:00+00:00                        NaN    1 min per ep
27328  2013-09-07T00:00:00+00:00  2014-08-23T00:00:00+00:00    1 min per ep
27371  1991-11-01T00:00:00+00:00  2003-11-01T00:00:00+00:00   15 sec per ep
27381  2008-01-16T00:00:00+00:00  2008-10-08T00:00:00+00:00   30 sec per ep
27613  2010-01-01T00:00:00+00:00                        NaN    1 min per ep

       score  scored_by  rank                     rating  \
735     7.96     4050.0   NaN  PG-13 - Teens 13 or older
1584    7.62     7015.0   NaN  PG-13 - Teens 13 or older
1998    7.52     2100.0   NaN               G - All Ages
2131    7.48     3825.0   NaN  PG-13 - Teens 13 or older
2973    7.31    38982.0   NaN               G - All Ages
...      ...        ...   ...                        ...
27286    NaN        NaN   NaN               G - All Ages
27328    NaN        NaN   NaN  PG-13 - Teens 13 or older
27371    NaN        NaN   NaN               G - All Ages
27381    NaN        NaN   NaN               G - All Ages
27613    NaN        NaN   NaN               G - All Ages

                                                 studios  \
735                                      Kyoto Animation
1584   ufotable, Shaft, A-1 Pictures, SILVER LINK., L...
1998                                               Shuka
2131                                         Flat Studio
2973                                    CoMix Wave Films
...                                                  ...
27286                                                NaN
27328                                                DLE
27371                                                NaN
27381                                   Studio Crocodile
27613                                                NaN

                            producers  \
735                               NaN
1584                              .MP
1998   Nihon Ad Systems, Ai Addiction
2131                              NaN
2973                The Answer Studio
...                               ...
27286                     Opera House
27328                             NaN
27371                             NaN
27381                             NaN
27613                             NaN

                                                   image  \
735    https://cdn.myanimelist.net/images/anime/1485/...
1584   https://cdn.myanimelist.net/images/anime/1554/...
1998   https://cdn.myanimelist.net/images/anime/1333/...
2131   https://cdn.myanimelist.net/images/anime/1794/...
2973   https://cdn.myanimelist.net/images/anime/1569/...
...                                                  ...
27286  https://cdn.myanimelist.net/images/anime/9/715...
27328  https://cdn.myanimelist.net/images/anime/1368/...
27371  https://cdn.myanimelist.net/images/anime/3/705...
27381  https://cdn.myanimelist.net/images/anime/1278/...
27613  https://cdn.myanimelist.net/images/anime/1270/...

                                           trailer  \
735                                            NaN
1584                                           NaN
1998                                           NaN
2131                                           NaN
2973   https://www.youtube.com/watch?v=AfbNS_GKhPw
...                                            ...
27286                                          NaN
27328                                          NaN
27371                                          NaN
27381                                          NaN
27613                                          NaN

                                                synopsis
735    Special trailers released on YouTube announcin...
1584   Assorted commercials and collaborations for th...
1998   Takashi Natsume and his loyal feline protector...
2131   The story follows three friends grappling with...
2973   As college entrance examinations draw near, tw...
...                                                  ...
27286                              A series of shorts fo
27328  Pittarazu-themed manner movies shown at T-JOY ...
27371  A commercial campaign by NEC to sell various g...
27381  Animated TV commercials for the Nissan Note fe...
27613                                                NaN

[504 rows x 18 columns]
Movie
          id                                               name  \
6      39486                            Gintama: The Very Final
17     28851                                     A Silent Voice
20     15335  Gintama: The Movie: The Final Chapter: Be Fore...
27     37987                       Violet Evergarden: The Movie
29     32281                                         Your Name.
...      ...                                                ...
28818  16804                        Super Metal Robot Solar 123
28819  16800             Miraesonyeon Kunta Beomyuda 5000 Nyeon
28820  16796                               Mujeokcheorin Rambot
28822  16790                                   Super Samchongsa
28824  16784                                            Marin X

                              genres   type  episodes           status  \
6      Action, Comedy, Drama, Sci-Fi  Movie       1.0  Finished Airing
17              Award Winning, Drama  Movie       1.0  Finished Airing
20            Action, Comedy, Sci-Fi  Movie       1.0  Finished Airing
27              Award Winning, Drama  Movie       1.0  Finished Airing
29              Award Winning, Drama  Movie       1.0  Finished Airing
...                              ...    ...       ...              ...
28818                         Action  Movie       1.0  Finished Airing
28819              Action, Adventure  Movie       1.0  Finished Airing
28820                 Action, Sci-Fi  Movie       1.0  Finished Airing
28822                 Action, Sci-Fi  Movie       1.0  Finished Airing
28824      Action, Adventure, Sci-Fi  Movie       1.0  Finished Airing

                      aired_from aired_to duration_per_ep  score  scored_by  \
6      2021-01-08T00:00:00+00:00      NaN     1 hr 44 min   9.04    80788.0
17     2016-09-17T00:00:00+00:00      NaN     2 hr 10 min   8.93  1714673.0
20     2013-07-06T00:00:00+00:00      NaN     1 hr 50 min   8.90   141157.0
27     2020-09-18T00:00:00+00:00      NaN     2 hr 20 min   8.84   313009.0
29     2016-08-26T00:00:00+00:00      NaN     1 hr 46 min   8.83  2004194.0
...                          ...      ...             ...    ...        ...
28818  1982-12-01T00:00:00+00:00      NaN     1 hr 15 min    NaN        NaN
28819  1983-01-01T00:00:00+00:00      NaN     1 hr 15 min    NaN        NaN
28820  1985-01-01T00:00:00+00:00      NaN     1 hr 10 min    NaN        NaN
28822  1982-01-01T00:00:00+00:00      NaN     1 hr 16 min    NaN        NaN
28824  1982-01-01T00:00:00+00:00      NaN     1 hr 20 min    NaN        NaN

          rank                     rating                studios  \
6          6.0  PG-13 - Teens 13 or older  Bandai Namco Pictures
17        18.0  PG-13 - Teens 13 or older        Kyoto Animation
20        21.0  PG-13 - Teens 13 or older                Sunrise
27        28.0  PG-13 - Teens 13 or older        Kyoto Animation
29        29.0  PG-13 - Teens 13 or older       CoMix Wave Films
...        ...                        ...                    ...
28818  14737.0                        NaN                    NaN
28819  18130.0                        NaN                    NaN
28820  18282.0                        NaN                    NaN
28822  14907.0                        NaN                    NaN
28824  17871.0                        NaN                    NaN

                                               producers  \
6      TV Tokyo, Aniplex, Dentsu, Bandai, Warner Bros...
17     Shochiku, Pony Canyon, Kodansha, ABC Animation...
20     TV Tokyo, Aniplex, Dentsu, Bandai, Warner Bros...
27                               Shochiku, ABC Animation
29     TOHO, Sound Team Don Juan, Lawson HMV Entertai...
...                                                  ...
28818                                                NaN
28819                                                NaN
28820                                                NaN
28822                                                NaN
28824                                                NaN

                                                   image  \
6      https://cdn.myanimelist.net/images/anime/1245/...
17     https://cdn.myanimelist.net/images/anime/1122/...
20     https://cdn.myanimelist.net/images/anime/10/51...
27     https://cdn.myanimelist.net/images/anime/1825/...
29     https://cdn.myanimelist.net/images/anime/5/870...
...                                                  ...
28818  https://cdn.myanimelist.net/images/anime/5/451...
28819  https://cdn.myanimelist.net/images/anime/6/451...
28820  https://cdn.myanimelist.net/images/anime/5/451...
28822  https://cdn.myanimelist.net/images/anime/13/45...
28824  https://cdn.myanimelist.net/images/anime/13/45...

                                           trailer  \
6      https://www.youtube.com/watch?v=Zn1filVUyf8
17     https://www.youtube.com/watch?v=XBNWo25izJ8
20     https://www.youtube.com/watch?v=UhJM5rVqaF8
27     https://www.youtube.com/watch?v=NSIzsFOfd8M
29     https://www.youtube.com/watch?v=3KR8_igDs1Y
...                                            ...
28818                                          NaN
28819                                          NaN
28820                                          NaN
28822                                          NaN
28824                                          NaN

                                                synopsis
6      Two years have passed following the Tendoshuu'...
17     As a wild youth, elementary school student Sho...
20     When Gintoki apprehends a movie pirate at a pr...
27     Several years have passed since the end of The...
29     Mitsuha Miyamizu, a high school girl, yearns t...
...                                                  ...
28818                                                NaN
28819  Kunta and his pet pelican set out on a journey to
28820                                                NaN
28822  A Korean animated movie about three kids prote...
28824             A Korean animated movie mixing Mecha w

[4836 rows x 18 columns]
Music
          id                         name                   genres   type  \
34     55255                  Alien Stage  Drama, Sci-Fi, Suspense  Music
53     55016                         Idol                      NaN  Music
275    48653        Racing into the Night                      NaN  Music
282    39112              Crying for Rain                      NaN  Music
285    42984                      Gotcha!                  Fantasy  Music
...      ...                          ...                      ...    ...
28024  43761                    Nemui Inu                   Comedy  Music
28029  43768                        Gifts                      NaN  Music
28037  43787          Ohirune no Yurikago                      NaN  Music
28067  43917                Viola wa Utau                      NaN  Music
28212  45031  Yoiko no Tanoshii Christmas                      NaN  Music

       episodes            status                 aired_from aired_to  \
34          NaN  Currently Airing  2022-09-07T00:00:00+00:00      NaN
53          1.0   Finished Airing  2023-04-12T00:00:00+00:00      NaN
275         1.0   Finished Airing  2019-11-16T00:00:00+00:00      NaN
282         1.0   Finished Airing  2019-01-29T00:00:00+00:00      NaN
285         1.0   Finished Airing  2020-09-29T00:00:00+00:00      NaN
...         ...               ...                        ...      ...
28024       1.0   Finished Airing  2014-02-02T00:00:00+00:00      NaN
28029       1.0   Finished Airing  2018-08-01T00:00:00+00:00      NaN
28037       1.0   Finished Airing  1995-12-01T00:00:00+00:00      NaN
28067       1.0   Finished Airing  2010-06-01T00:00:00+00:00      NaN
28212       9.0   Finished Airing  1987-01-01T00:00:00+00:00      NaN

      duration_per_ep  score  scored_by  rank                          rating  \
34              3 min   8.79     3060.0   NaN  R - 17+ (violence & profanity)
53              3 min   8.72    18645.0   NaN       PG-13 - Teens 13 or older
275             4 min   8.32    12106.0   NaN       PG-13 - Teens 13 or older
282             4 min   8.31    18800.0   NaN       PG-13 - Teens 13 or older
285             3 min   8.31    20119.0   NaN                   PG - Children
...               ...    ...        ...   ...                             ...
28024           2 min    NaN        NaN   NaN                    G - All Ages
28029           4 min    NaN        NaN   NaN                    G - All Ages
28037           2 min    NaN        NaN   NaN                    G - All Ages
28067           2 min    NaN        NaN   NaN                    G - All Ages
28212    2 min per ep    NaN        NaN   NaN                    G - All Ages

              studios                 producers  \
34               LICO                       NaN
53          Doga Kobo                       NaN
275               NaN  Sony Music Entertainment
282               NaN                       NaN
285             Bones                       NaN
...               ...                       ...
28024             NaN                       NHK
28029             NaN                       NHK
28037         Three-d                       NHK
28067     Super Brain                       NHK
28212  Oh! Production              King Records

                                                   image trailer  \
34     https://cdn.myanimelist.net/images/anime/1524/...     NaN
53     https://cdn.myanimelist.net/images/anime/1921/...     NaN
275    https://cdn.myanimelist.net/images/anime/1548/...     NaN
282    https://cdn.myanimelist.net/images/anime/1776/...     NaN
285    https://cdn.myanimelist.net/images/anime/1637/...     NaN
...                                                  ...     ...
28024  https://cdn.myanimelist.net/images/anime/1484/...     NaN
28029  https://cdn.myanimelist.net/images/anime/1327/...     NaN
28037  https://cdn.myanimelist.net/images/anime/1360/...     NaN
28067  https://cdn.myanimelist.net/images/anime/1438/...     NaN
28212  https://cdn.myanimelist.net/images/anime/1362/...     NaN

                                                synopsis
34     Humans once lived like Earth was the center of...
53                                       Music video for
275                             Music video of the song
282                            Music video for the song
285    In a bright, grandiose city, a young boy and g...
...                                                  ...
28024  Music video for the song Nemui Inu by Osamu Sa...
28029  Music video for the song Gifts by Japanese roc...
28037  Music video for the song Ohirune no Yurikago b...
28067  Music video for the song Viola wa Utau by Nori...
28212          A direct-to-video collection of nine Chri

[4087 rows x 18 columns]
ONA
          id                                        name  \
57     44074                                  Link Click
70     40434                   The Master of Diabolism 3
71     57864     Monogatari Series: Off & Monster Season
77     49413                         Link Click Season 2
79     50399         Heaven Official's Blessing Season 2
...      ...                                         ...
28786  48754                         Lie Yang Tiandao II
28806  48844                                   Call Star
28812  48851                 Zhandouban Geji! 2nd Season
28815  48852                Zhandouban Geji! Season Zero
28821  48866  Hua Jianghu: Huan Shi Men Sheng 2nd Season

                                           genres type  episodes  \
57                       Drama, Mystery, Suspense  ONA      11.0
70     Action, Adventure, Drama, Fantasy, Mystery  ONA      12.0
71                  Comedy, Mystery, Supernatural  ONA      14.0
77                       Drama, Mystery, Suspense  ONA      12.0
79              Action, Adventure, Drama, Fantasy  ONA      12.0
...                                           ...  ...       ...
28786          Action, Adventure, Fantasy, Sci-Fi  ONA       1.0
28806                             Comedy, Fantasy  ONA      12.0
28812                       Comedy, Slice of Life  ONA      14.0
28815                       Comedy, Slice of Life  ONA       4.0
28821            Drama, Fantasy, Mystery, Romance  ONA      19.0

                status                 aired_from                   aired_to  \
57     Finished Airing  2021-04-30T00:00:00+00:00  2021-07-09T00:00:00+00:00
70     Finished Airing  2021-08-07T00:00:00+00:00  2021-10-16T00:00:00+00:00
71     Finished Airing  2024-07-06T00:00:00+00:00  2024-10-19T00:00:00+00:00
77     Finished Airing  2023-07-14T00:00:00+00:00  2023-09-22T00:00:00+00:00
79     Finished Airing  2023-10-18T00:00:00+00:00  2024-01-17T00:00:00+00:00
...                ...                        ...                        ...
28786  Finished Airing  2021-02-12T00:00:00+00:00                        NaN
28806  Finished Airing  2021-04-19T00:00:00+00:00  2021-07-05T00:00:00+00:00
28812  Finished Airing  2019-04-10T00:00:00+00:00  2019-07-12T00:00:00+00:00
28815  Finished Airing  2018-10-04T00:00:00+00:00  2018-10-07T00:00:00+00:00
28821  Finished Airing  2021-05-12T00:00:00+00:00  2021-08-25T00:00:00+00:00

      duration_per_ep  score  scored_by     rank  \
57      23 min per ep   8.72   170545.0     55.0
70      24 min per ep   8.68    32395.0     66.0
71      25 min per ep   8.67    32314.0     72.0
77      24 min per ep   8.65    67211.0     76.0
79      24 min per ep   8.65    21019.0     76.0
...               ...    ...        ...      ...
28786      1 hr 7 min    NaN        NaN  17638.0
28806   10 min per ep    NaN        NaN  15631.0
28812    7 min per ep    NaN        NaN  16528.0
28815    8 min per ep    NaN        NaN  16529.0

In [14]:
f =df[df["type"]=="TV"].sum()
for i,v in f:
    print(v)

TypeError: cannot unpack non-iterable numpy.int64 object

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28825 entries, 0 to 28824
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               28825 non-null  int64
 1   name             28825 non-null  str
 2   genres           22756 non-null  str
 3   type             28738 non-null  str
 4   episodes         28046 non-null  float64
 5   status           28825 non-null  str
 6   aired_from       27870 non-null  str
 7   aired_to         10930 non-null  str
 8   duration_per_ep  28825 non-null  str
 9   score            18599 non-null  float64
 10  scored_by        18599 non-null  float64
 11  rank             21962 non-null  float64
 12  rating           28101 non-null  str
 13  studios          16936 non-null  str
 14  producers        13452 non-null  str
 15  image            28825 non-null  str
 16  trailer          5474 non-null   str
 17  synopsis         23457 non-null  str
dtypes: float64(4), int64(1), str(13)
memory usage: 4.0 MB