In [ ]:
import numpy as np
import pandas as pd
arr = np.array([1,2])
print(arr)

[1 2]

In [9]:
import numpy as np
import pandas as pd
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}
# pd.Series(my_list,index=labels)
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [10]:
data = {
    "name": ["Rahim", "Karim", "Arafat"],
    "age": [25, 30, 22],
    "city": ["Dhaka", "Chittagong", "Khulna"],
    "salary": [50000, 60000, 45000]
}

pd.DataFrame(data)

     name  age        city  salary
0   Rahim   25       Dhaka   50000
1   Karim   30  Chittagong   60000
2  Arafat   22      Khulna   45000

In [11]:
data_list = [
    ["Rahim", 25, "Dhaka", 50000],
    ["Karim", 30, "Chittagong", 60000],
    ["Arafat", 22, "Khulna", 45000]
]
df = pd.DataFrame(data_list)
df

        0   1           2      3
0   Rahim  25       Dhaka  50000
1   Karim  30  Chittagong  60000
2  Arafat  22      Khulna  45000

In [12]:
data_list = [
    {"name": "Rahim", "age": 25, "city": "Dhaka", "salary": 50000},
    {"name": "Karim", "age": 30, "city": "Chittagong", "salary": 60000},
    {"name": "Arafat", "age": 22, "city": "Khulna", "salary": 45000}
]
df1 = pd.DataFrame(data_list)
df1

     name  age        city  salary
0   Rahim   25       Dhaka   50000
1   Karim   30  Chittagong   60000
2  Arafat   22      Khulna   45000

In [13]:
df1["name"]

0     Rahim
1     Karim
2    Arafat
Name: name, dtype: str

In [17]:
df1[["name","age"]]

     name  age
0   Rahim   25
1   Karim   30
2  Arafat   22

In [20]:
df1["About"] = ["cse","EEE","civil"]
df1

     name  age        city  salary  About
0   Rahim   25       Dhaka   50000    cse
1   Karim   30  Chittagong   60000    EEE
2  Arafat   22      Khulna   45000  civil

In [27]:
df1.drop("About",axis=1,inplace=True)
df1

KeyError: "['About'] not found in axis"

In [26]:
df1

     name  age        city  salary
0   Rahim   25       Dhaka   50000
1   Karim   30  Chittagong   60000
2  Arafat   22      Khulna   45000

In [28]:
 df1

     name  age        city  salary
0   Rahim   25       Dhaka   50000
1   Karim   30  Chittagong   60000
2  Arafat   22      Khulna   45000

In [31]:
df1.loc[[0,1]]

    name  age        city  salary
0  Rahim   25       Dhaka   50000
1  Karim   30  Chittagong   60000

In [32]:
df1.loc[[0,1]][["city","salary"]]

         city  salary
0       Dhaka   50000
1  Chittagong   60000

In [35]:
df1

     name  age        city  salary
0   Rahim   25       Dhaka   50000
1   Karim   30  Chittagong   60000
2  Arafat   22      Khulna   45000

In [40]:
df1.loc[[1,2]][["age","salary"]]

   age  salary
1   30   60000
2   22   45000

In [42]:
df1[df1["age"]>26]

    name  age        city  salary
1  Karim   30  Chittagong   60000